# Generated by Django 3.2.18 on 2024-04-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20240320_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amont_paid',
            new_name='amount_paid',
        ),
    ]
